project:
  type: website

website:
  title: "Final Project - Sev"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - model.qmd
      - eda.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

