```         
```

---
title: "Penguins EDA"

format:

  html:

    code-fold: true
---

\## Penguin Size and Mass by Sex and Species

```{r}
#install.packages("palmerpenguins")
#install.packages("dplyr")
#install.packages("renv")

library(palmerpenguins)
library(dplyr)
library(dbplyr)
library(ggplot2)
library(DBI)
library(duckdb)

#con <- DBI::dbConnect(duckdb::duckdb(), dbdir = "my-db.duckdb")
#DBI::dbWriteTable(con, "penguins", palmerpenguins::penguins)
#DBI::dbDisconnect(con)


df <- palmerpenguins::penguins

#con <- DBI::dbConnect(duckdb::duckdb(), dbdir = "my-db.duckdb")


#df <- dplyr::tbl(con, "penguins")

#df <- palmerpenguins::penguins
```

```{r}
df %>%

  group_by(species, sex) %>%

  summarise(

    across(

        ends_with("mm") | ends_with("g"),

      \(x) mean(x, na.rm = TRUE)

      )

    ) %>%

  dplyr::collect() %>%

  knitr::kable()
```

\## Penguin Size vs Mass by Species

```{r}
df %>%

  ggplot(aes(x = bill_length_mm, y = body_mass_g, color = species)) +

  geom_point() + 

  geom_smooth(method = "lm")
```

```{r}
#DBI::dbDisconnect(con, shutdown = TRUE)
```
